#Conditional statements in python

#conditional statements: Controlling the flow of execution.
             1.if
             2.if else
             3.elif

#Loops in Python
            1.For
            2.While

# Strings
            1.Declaring a string
            2.Accessing a string
            3.String methods

Syntax of if:
    if condition1:
        Block code of code

Biggest numbers program

In [3]:
a=55
b=100
if a>b:
    print(a,"is the biggest number")
    
else:
    print(b,"is the biggest number")

100 is the biggest number

In [5]:
a=int(input("enter the number:"))
if a%2==0:
    print("even")
else:
    print("odd")

enter the number:68
even

In [16]:
n=int(input("Enter the year:"))
if n%400==0 or n%4==0 and n%100!=0:
    print("it is a leap year")
else:
    print("it is not a leap year")

Enter the year:2023
it is not a leap year

# calculator

In [19]:
a=int(input("enter the number:"))
b=int(input("enter the another number:"))
x=input("which arithmetic operation you want to perform:")
if x=="add":
    print("sum of the two numbers is", a+b)
elif x=="sub":
    print("difference of the two numbers is",a-b)
elif x=="mul":
    print("Multiplication of the two numbers is ",a*b)
else:
    print("enter the valid number:")

enter the number:123
enter the another number:456
which arithmetic operation you want to perform:add
sum of the two numbers is 579

##  loops in python

for iterable variable in sequence of data
           Block of code........

In [22]:
for i in range(1,101,2):
    print(i,end='\t')

1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	33	35	37	39	41	43	45	47	49	51	53	55	57	59	61	63	65	67	69	71	73	75	77	79	81	83	85	87	89	91	93	95	97	99

In [28]:
for i in range(1,1000,1):
    if i%2==0:
        print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510
512
514
516
518
520
522
524
526
528
530
532
534
536
538
540
542
544
546
548
550
552
554
556
558
560
562
564
566
568
570
572
574
576
578
580
582
584
586
588
590
592
594
596
598
600
602
604
606
608
610
612
614
616
618
620
622
624
626
628
630
632
634
636
638
640
642
644
646
648
650
652
654
656
658
660
662
664
666
668
670
672
674
676
678
680
682
684
686
688
690
692
694
696
698
700
702
704
706
708
710
712
714
716
718
720
722
724
726
728
730
732
734
736
738
740
742
744
746
748
750
752
754
756
758
760
762
764
766
768
770
772
774
776
778
780
782
784
786
788
790
792
794
796
798
800
802
804
806
808
810
812
814
816
818
820
822
824
826
828
830
832
834
836
838
840
842
844
846
848
850
852
854
856
858
860
862
864
866
868
870
872
874
876
878
880
882
884
886
888
890
892
894
896
898
900
902
904
906
908
910
912
914
916
918
920
922
924
926
928
930
932
934
936
938
940
942
944
946
948
950
952
954
956
958
960
962
964
966
968
970
972
974
976
978
980
982
984
986
988
990
992
994
996
998

# leap year

In [40]:
range1=int(input("enter the starting range:"))
range2=int(input("enter the ending range:"))
for i in range(range1,range2,1):
    if i%400==0 or i%4==0 and i%100!=0:
        print(i)

enter the starting range:1800
enter the ending range:2000
1804
1808
1812
1816
1820
1824
1828
1832
1836
1840
1844
1848
1852
1856
1860
1864
1868
1872
1876
1880
1884
1888
1892
1896
1904
1908
1912
1916
1920
1924
1928
1932
1936
1940
1944
1948
1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996

In [38]:
for travel in range(0,101,1):
    if travel==50:
        break
    elif travel%2==0:
        continue
    print(travel,end='\t')

1	3	5	7	9	11	13	15	17	19	21	23	25	27	29	31	33	35	37	39	41	43	45	47	49

# strings: A group of characters in a letter beyween '''',"""",'''' ''''.




  * It is immuterable data type
  ** It is iterable

In [48]:
s="My name Is subhash teja"
lo=0
uo=0
c=0
for char in s:
    if char in 'aeiou':
        lo+=1
    elif char in 'AEIOU':
        uo+=1
    else:
        c+=1
print(uo,"Upper case vowels",lo,"lower case vowels")

1 Upper case vowels 6 lower case vowels

In [49]:
print(s[-1])

a